export const EmojiClasses = {
  Plant: '🍀',
  Reptile: '🦎',
  Beast: '🦁',
  Aquatic: '🐟',
  Bird: '🦅',
  Bug: '🐞',
  Dusk: '🌙',
  Mesk: '💠',
  Dawn: '✨',
}

export const EmojiStats = {
  hp: '🔋',
  speed: '💨',
  skill: '💡',
  morale: '💢',
}

export const AxieClasses = Object.keys(EmojiClasses)

export const AxieBodyParts = {
  mouth: '',
  back: '',
  tail: '',
  horn: '',
}

export const AxiePartNames = {
  'mouth-catfish': 'Aquatic',
  'back-hermit': 'Aquatic',
  'back-goldfish': 'Aquatic',
  'tail-nimo': 'Aquatic',
  'horn-shoal-star': 'Aquatic',
  'mouth-lam': 'Aquatic',
  'mouth-risky-fish': 'Aquatic',
  'back-perch': 'Aquatic',
  'mouth-piranha': 'Aquatic',
  'horn-oranda': 'Aquatic',
  'back-anemone': 'Aquatic',
  'tail-navaga': 'Aquatic',
  'horn-anemone': 'Aquatic',
  'back-sponge': 'Aquatic',
  'tail-koi': 'Aquatic',
  'tail-shrimp': 'Aquatic',
  'horn-clamshell': 'Aquatic',
  'tail-ranchu': 'Aquatic',
  'horn-teal-shell': 'Aquatic',
  'horn-babylonia': 'Aquatic',
  'tail-tadpole': 'Aquatic',
  'back-blue-moon': 'Aquatic',
  'mouth-nut-cracker': 'Beast',
  'mouth-goda': 'Beast',
  'tail-nut-cracker': 'Beast',
  'horn-imp': 'Beast',
  'back-ronin': 'Beast',
  'horn-dual-blade': 'Beast',
  'horn-arco': 'Beast',
  'tail-cottontail': 'Beast',
  'back-risky-Beast': 'Beast',
  'back-jaguar': 'Beast',
  'horn-little-branch': 'Beast',
  'tail-hare': 'Beast',
  'tail-rice': 'Beast',
  'tail-shiba': 'Beast',
  'mouth-confident': 'Beast',
  'horn-pocky': 'Beast',
  'horn-merry': 'Beast',
  'tail-gerbil': 'Beast',
  'mouth-axie-kiss': 'Beast',
  'back-timber': 'Beast',
  'back-furball': 'Beast',
  'back-hero': 'Beast',
  'tail-post-fight': 'Bird',
  'back-pigeon-post': 'Bird',
  'horn-eggshell': 'Bird',
  'horn-kestrel': 'Bird',
  'back-raven': 'Bird',
  'mouth-peace-maker': 'Bird',
  'back-cupid': 'Bird',
  'tail-granmas-fan': 'Bird',
  'mouth-little-owl': 'Bird',
  'mouth-hungry-Bird': 'Bird',
  'back-balloon': 'Bird',
  'mouth-doubletalk': 'Bird',
  'tail-swallow': 'Bird',
  'horn-trump': 'Bird',
  'horn-wing-horn': 'Bird',
  'back-tri-feather': 'Bird',
  'horn-feather-spear': 'Bird',
  'tail-feather-fan': 'Bird',
  'tail-the-last-one': 'Bird',
  'tail-cloud': 'Bird',
  'horn-cuckoo': 'Bird',
  'back-kingfisher': 'Bird',
  'back-scarab': 'Bug',
  'mouth-mosquito': 'Bug',
  'back-snail-shell': 'Bug',
  'tail-fish-snack': 'Bug',
  'horn-leaf-Bug': 'Bug',
  'tail-thorny-cattepilar': 'Bug',
  'horn-parasite': 'Bug',
  'back-spiky-wing': 'Bug',
  'mouth-cute-bunny': 'Bug',
  'horn-antenna': 'Bug',
  'horn-caterpillars': 'Bug',
  'horn-laggin': 'Bug',
  'horn-pliers': 'Bug',
  'back-sandal': 'Bug',
  'back-buzz-buzz': 'Bug',
  'back-garish-worm': 'Bug',
  'tail-ant': 'Bug',
  'mouth-square-teeth': 'Bug',
  'tail-gravel-ant': 'Bug',
  'tail-pupae': 'Bug',
  'tail-twin-tail': 'Bug',
  'mouth-pincer': 'Bug',
  'mouth-herbivore': 'Plant',
  'mouth-zigzag': 'Plant',
  'horn-rose-bud': 'Plant',
  'back-shiitake': 'Plant',
  'mouth-silence-whisper': 'Plant',
  'horn-strawberry-shortcake': 'Plant',
  'horn-beech': 'Plant',
  'back-pumpkin': 'Plant',
  'tail-carrot': 'Plant',
  'mouth-serious': 'Plant',
  'horn-cactus': 'Plant',
  'back-bidens': 'Plant',
  'back-mint': 'Plant',
  'tail-hot-butt': 'Plant',
  'back-watering-can': 'Plant',
  'horn-watermelon': 'Plant',
  'tail-hatsune': 'Plant',
  'horn-bamboo-shoot': 'Plant',
  'tail-potato-leaf': 'Plant',
  'tail-yam': 'Plant',
  'back-turnip': 'Plant',
  'tail-cattail': 'Plant',
  'mouth-razor-bite': 'Reptile',
  'back-green-thorns': 'Reptile',
  'tail-snake-jar': 'Reptile',
  'horn-bumpy': 'Reptile',
  'back-red-ear': 'Reptile',
  'back-bone-sail': 'Reptile',
  'back-rugged-sail': 'Reptile',
  'mouth-tiny-turtle': 'Reptile',
  'back-tri-spikes': 'Reptile',
  'tail-wall-gecko': 'Reptile',
  'tail-escaped-gecko': 'Reptile',
  'horn-incisor': 'Reptile',
  'horn-cerastes': 'Reptile',
  'back-croc': 'Reptile',
  'mouth-kotaro': 'Reptile',
  'horn-scaly-spear': 'Reptile',
  'mouth-toothless-bite': 'Reptile',
  'mouth-venom-bite': 'Reptile',
  'horn-scaly-spoon': 'Reptile',
  'tail-gila': 'Reptile',
  'tail-tiny-dino': 'Reptile',
  'back-indian-star': 'Reptile',
  'tail-grass-snake': 'Reptile',
  'horn-unko': 'Reptile',
  'horn-pinku-unko': 'Reptile',
}

export const AxieParts = Object.keys(AxiePartNames)

export default EmojiClasses
